"""
Signals API — serves real signals from the engine.
Reads signals_today_weekly.json (generated by daily_runner.py).
Also provides on-demand scan via POST /api/signals/scan and regime info.
"""

import json
import logging
import os
from pathlib import Path
from datetime import datetime, date

import requests
from fastapi import APIRouter, Depends, HTTPException, Query, Request
from slowapi import Limiter
from slowapi.util import get_remote_address
from sqlalchemy.orm import Session

from auth import get_current_user
from config import get_sector
from database import User, get_db

limiter = Limiter(key_func=get_remote_address)

logger = logging.getLogger("niftyquant.signals")

router = APIRouter(tags=["signals"])

# Paths — try multiple locations (local dev vs Render deployment)
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent  # c:\project
RESULTS_DIR = PROJECT_ROOT / "results"
MODELS_DIR = PROJECT_ROOT / "models"
# Re-pointed 2026-07-01: results/* (signals_today_weekly.json etc.) now live in the
# clean nifty-satvik engine repo, pushed by its paper-book cron.
GITHUB_RAW = "https://raw.githubusercontent.com/kreeshpatel/nifty-satvik/main"
# The repo is PRIVATE — raw.githubusercontent URLs 404 without auth. Read
# cron-published results/ files through the authenticated GitHub API contents
# endpoint instead, using the same GITHUB_TOKEN the cron uses to push.
GITHUB_API_CONTENTS = "https://api.github.com/repos/kreeshpatel/nifty-satvik/contents"

# ── The single live model (the momentum book was fully removed 2026-07-13) ──
# `bhanushali` = the Bhanushali weekly-swing book — the only live model. Written by
#                scripts/run_bhanushali_cron.py. Internal result files keep their
#                *_weekly.* names (the cron's git-commit list is keyed to them);
#                the model is named "bhanushali" everywhere a user/dev sees it.
# `weekly`     = back-compat alias for `bhanushali` (older links / cached clients).
_MODELS = {
    "bhanushali": {
        "today": "signals_today_weekly.json", "history": "signals_history_weekly.json",
        "analytics": "signal_analytics_weekly.json", "portfolio": "paper_portfolio_weekly.json",
        "watchlist": None, "config": "models/bhanushali_weekly/config.json",
    },
}
# Back-compat: `?model=weekly` resolves to the same Bhanushali book.
_MODELS["weekly"] = _MODELS["bhanushali"]

# Model names that mean the Bhanushali weekly-swing book (for the monitor overlay).
_BHANUSHALI_ALIASES = {"bhanushali", "weekly"}


def _model_or_400(model: str) -> dict:
    m = _MODELS.get(model)
    if m is None:
        raise HTTPException(status_code=400,
                            detail=f"Unknown model '{model}'. Use 'bhanushali'.")
    return m


import time as _time

# In-memory cache for GitHub raw fetches. Keyed by repo-relative path,
# value is (timestamp, parsed_json). 30s TTL is generous: the cron runs
# once per day, so a fetch within 30s of the prior fetch will return
# the same data anyway. Saves ~200ms per request under load and
# protects against GitHub raw rate limits during traffic spikes.
_GITHUB_CACHE: dict[str, tuple[float, object]] = {}
_GITHUB_CACHE_TTL = 30.0


def _fetch_github_raw(github_path: str):
    """Fetch JSON for a cron-published results/ file from the PRIVATE repo via the
    authenticated GitHub API contents endpoint, with a 30s in-memory cache.

    Returns None on any failure (incl. missing GITHUB_TOKEN) so the caller falls
    back to the local file. Since the repo went private, the old unauthenticated
    raw.githubusercontent URL 404s — this keeps live signal data fresh on Render.
    """
    now = _time.time()
    cached = _GITHUB_CACHE.get(github_path)
    if cached and (now - cached[0]) < _GITHUB_CACHE_TTL:
        return cached[1]
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        # No token on this service → can't read the private repo. Caller will
        # use the local file. (Set GITHUB_TOKEN on the web service to enable.)
        return None
    try:
        r = requests.get(
            f"{GITHUB_API_CONTENTS}/{github_path}?ref=main",
            headers={
                "Authorization": f"token {token}",
                "Accept": "application/vnd.github.raw",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=10,
        )
        if r.status_code == 200:
            data = json.loads(r.text)
            _GITHUB_CACHE[github_path] = (now, data)
            return data
        logger.warning(f"GitHub API fetch {github_path} -> HTTP {r.status_code}")
    except Exception as e:
        logger.error(f"GitHub API fetch failed for {github_path}: {e}")
    return None


# Paths under results/ are written by the cron and pushed to GitHub
# externally — Render's local copy goes stale within minutes of every
# cron run because Render only refreshes its filesystem snapshot when
# the WEB SERVICE rebuilds, not when the cron pushes files. The
# practical fallout: the user sees "FAILED_TODAY" banners because the
# live API is reading yesterday's signals_today_weekly.json from local disk.
#
# So for results/* we PREFER GitHub (with the 30s cache above) and
# fall back to local only if GitHub is unreachable. For models/* and
# other code-shipped paths the original local-first behaviour is
# correct because those files are deploy-time artifacts.
def _read_json_with_fallback(path: Path, github_path: str, default=None):
    """Read JSON from cron-published results/ via GitHub (cached), fall
    back to local. Other paths read local first, GitHub second.

    The branch hinges on the github_path prefix — `results/...` is
    treated as cron-pushed canonical data; everything else is treated
    as deploy-time data living on disk.
    """
    is_results = github_path.startswith("results/")

    if is_results:
        # GitHub first — that's where the cron pushed.
        data = _fetch_github_raw(github_path)
        if data:
            return data
        # GitHub unreachable — fall through to local file (likely stale,
        # but better than 500-ing on a transient GH outage).
        try:
            if path.exists():
                with open(path) as f:
                    local = json.load(f)
                    if local:
                        return local
        except Exception as e:
            logger.error(f"Failed to read fallback {path}: {e}")
        return default

    # Non-results path — local first as before.
    try:
        if path.exists():
            with open(path) as f:
                data = json.load(f)
                if data:
                    return data
    except Exception as e:
        logger.error(f"Failed to read {path}: {e}")
    data = _fetch_github_raw(github_path)
    if data:
        return data
    return default


def _read_json(path: Path, default=None):
    """Safely read a JSON file."""
    try:
        if path.exists():
            with open(path) as f:
                return json.load(f)
    except Exception as e:
        logger.error(f"Failed to read {path}: {e}")
    return default


def _stamp_sector(signals: list) -> list:
    """Attach `sector` (config.SECTOR_MAP, 607 NSE tickers) to each signal
    that doesn't already carry one. Neither the momentum nor bhanushali cron
    writes a `sector` field into signals_today*.json, so without this every
    signal fell into the frontend's `s.sector || 'Other'` fallback — the
    Dashboard's Sector Breadth card always showed one giant 'Other' bubble
    instead of a real sector split."""
    out = []
    for s in signals:
        if s.get("sector"):
            out.append(s)
            continue
        copy = dict(s)
        copy["sector"] = get_sector(s.get("ticker", ""))
        out.append(copy)
    return out


def _overlay_weekly_monitor(signals: list, monitor: dict) -> tuple[list, dict]:
    """Overlay the daily observational monitor onto the frozen weekly cards.

    The weekly engine only recomputes Saturday, so each card's `current_price` is Saturday's.
    The daily monitor (results/weekly_monitor.json, written by scripts/run_bhanushali_monitor.py)
    re-prices those cards against fresh daily bars and flags intra-week events. Here we merge
    its live `current_price`/`close` and attach a per-card `monitor` block — WITHOUT touching
    the frozen entry/stop/target (those change only at the weekly close). Non-weekly models and
    a missing/empty monitor are no-ops.

    Returns (signals, meta) where meta carries the monitor's as-of stamp + fired flags so the
    frontend can show a freshness badge and an event banner without re-deriving them.
    """
    if not signals or not isinstance(monitor, dict):
        return signals, {}
    by_ticker = {m.get("ticker"): m for m in monitor.get("monitors", []) if m.get("ticker")}
    if not by_ticker:
        return signals, {}
    out = []
    for sig in signals:
        m = by_ticker.get(sig.get("ticker"))
        if not m:
            out.append(sig)
            continue
        enriched = dict(sig)
        if m.get("current_price") is not None:
            enriched["current_price"] = m["current_price"]
            enriched["close"] = m["current_price"]
        enriched["monitor"] = m
        out.append(enriched)
    meta = {
        "monitor_as_of": monitor.get("as_of"),
        "monitor_generated_ist": monitor.get("generated_ist"),
        "monitor_flags": monitor.get("flags", []),
    }
    return out, meta


def _stamp_actionability(signals: list) -> list:
    """Stamp `actionability` (BUY_OPEN / BUY_CLOSED / EXIT_REQUIRED) on each signal from the
    cron-written field, with a market-state fallback.

    The per-user Kite / nq-order position mapping was REMOVED 2026-07-13 — the Signals page shows the
    MODEL's own book (open / hold / exit), not any viewer's personal holdings. Held/exit state comes
    from the envelope itself (bought_date + status), written by the paper-book cron; no DB or Kite
    call is made here. Personal-holding tracking now lives only on the Positions page.
    """
    if not signals:
        return signals
    from services.nq_positions import _compute_actionability
    today = date.today()
    out = []
    for sig in signals:
        enriched = dict(sig)
        enriched["actionability"] = sig.get("actionability") or _compute_actionability(sig, today)
        out.append(enriched)
    return out


@router.get("/signals")
def get_signals(
    model: str = Query("bhanushali", description="Strategy book: 'bhanushali' (weekly-swing, live)"),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Get today's signals + regime + portfolio state + cron health.
    Reads from signals_today_weekly.json (envelope: {generated_at, signals, ...}).
    Falls back to GitHub if local file is missing (Render deployment).

    Each signal is augmented with `actionability` (read straight from the
    cron-written field, with a market-state fallback for signals that
    predate PR2) and `user_position` (per-(user, signal) state — held qty,
    avg fill, status_for_user, sell_guidance — joined live from
    nq_orders + Kite holdings via services/nq_positions).
    """
    files = _model_or_400(model)
    raw = _read_json_with_fallback(
        RESULTS_DIR / files["today"], f"results/{files['today']}", []
    )
    # Handle both new envelope and legacy array
    if isinstance(raw, list):
        signals = raw
        generated_at = None
        sizing_capital = None
        sizing_risk_pct = None
    else:
        signals = raw.get("signals", []) or []
        generated_at = raw.get("generated_at")
        sizing_capital = raw.get("sizing_capital")
        sizing_risk_pct = raw.get("sizing_risk_pct")

    signals = _stamp_sector(signals)

    # ── Daily observational overlay (weekly book only) ─────────────────
    # The weekly engine recomputes only Saturday, so `current_price` on each
    # card is up to a week stale mid-week. The daily monitor cron re-prices
    # the frozen cards and flags intra-week events; overlay it here so live
    # prices/P&L and events reach every viewer, Kite-connected or not,
    # without a second signal engine. Frozen entry/stop/target are untouched.
    monitor_meta: dict = {}
    review_scorecard = None
    if model in _BHANUSHALI_ALIASES:
        monitor = _read_json_with_fallback(
            RESULTS_DIR / "weekly_monitor.json", "results/weekly_monitor.json", {}
        )
        signals, monitor_meta = _overlay_weekly_monitor(signals, monitor or {})
        # Forward-review scorecard (Oct-1 promote/kill machinery, forward/prereg.md gates).
        review_scorecard = _read_json_with_fallback(
            RESULTS_DIR / "weekly_review_scorecard.json", "results/weekly_review_scorecard.json", None
        )

    portfolio = _read_json_with_fallback(
        RESULTS_DIR / files["portfolio"], f"results/{files['portfolio']}", {}
    )
    # The live strategy is the long-horizon (3-month) trend model (v1 retired
    # 2026-06-25). Read its frozen config for the dashboard model badge. It is a
    # rule-based composite, not a trained classifier, so there is no AUC /
    # per-feature count — those badge fields are left at safe defaults.
    _cfg_rel = files["config"]
    model_cfg = _read_json_with_fallback(
        PROJECT_ROOT / _cfg_rel, _cfg_rel, {}
    )
    model_meta = {
        "version": model_cfg.get("model_version", "long-horizon-63d"),
        "trained_at": model_cfg.get("params_derived_through"),
        "avg_auc": 0,
        "n_features": 0,
        "strategy": model_cfg.get("strategy", "LONG_HORIZON"),
        "horizon_days": model_cfg.get("horizon_days", 63),
    }

    # Read regime from the signals_today_weekly.json envelope. Previously this
    # block read regime_history.csv, but nothing in the live cron path
    # ever wrote that file — the legacy 5-tier engine/regime_detector.py
    # is orphaned. Result: dashboard rendered "Market is Unknown · VIX
    # 0.0 · Breadth 0%" while the v1 strategy was gating on real regime
    # values that never reached the UI. The cron now snapshots the v1
    # strategy's live regime into the envelope (see
    # cron_runner._build_regime_snapshot), so this read is a single
    # dict lookup with a graceful default.
    envelope_regime = (raw or {}).get("regime") if isinstance(raw, dict) else None
    if envelope_regime:
        regime_info = {
            "status": envelope_regime.get("status", "UNKNOWN"),
            "strength": envelope_regime.get("strength", 0),
            "vix": envelope_regime.get("vix", 0),
            "breadth": envelope_regime.get("breadth", 0),
        }
    else:
        # Pre-A3 envelope (or transient read failure) — neutral default.
        # Frontend treats UNKNOWN status as "no signal".
        regime_info = {"status": "UNKNOWN", "strength": 0, "vix": 0, "breadth": 0}

    # Scan timestamp: prefer envelope's generated_at, else file mtime
    signals_path = RESULTS_DIR / "signals_today_weekly.json"
    scan_time = generated_at
    if not scan_time and signals_path.exists():
        scan_time = datetime.fromtimestamp(signals_path.stat().st_mtime).isoformat()

    # Cron health: how recently did the scan run?
    #
    # Earlier this compared `today_utc_str` (UTC date) against the scan's
    # date prefix. That breaks because the cron runs on an IST schedule
    # (4:15 PM IST = 10:45 UTC) — UTC midnight rolls over BEFORE the
    # next cron, so between 00:00 and 10:45 UTC (5:30 AM to 4:15 PM
    # IST), yesterday's perfectly-fresh scan was being flagged "STALE"
    # for 11 hours during IST business hours. Replaced with an
    # age-based threshold tied to the scheduled cadence.
    #
    # Thresholds:
    #   age <= 26h on a trading day → OK    (within one cycle + 2h grace)
    #   age <= 48h                  → FAILED_TODAY (one cycle missed)
    #   age >  48h                  → STALE (multiple days behind)
    now_utc = datetime.utcnow()
    today_utc_str = now_utc.strftime("%Y-%m-%d")
    is_trading_day = now_utc.weekday() < 5
    try:
        from config import NSE_HOLIDAYS
        if today_utc_str in NSE_HOLIDAYS:
            is_trading_day = False
    except Exception:
        pass

    scan_age_hours: float | None = None
    if scan_time:
        try:
            # Tolerate either ISO with 'Z' or a naive UTC ISO string.
            scan_dt = datetime.fromisoformat(scan_time.replace("Z", "+00:00"))
            if scan_dt.tzinfo is not None:
                scan_dt = scan_dt.replace(tzinfo=None)
            scan_age_hours = (now_utc - scan_dt).total_seconds() / 3600
        except Exception:
            pass

    last_run_today = bool(scan_time and scan_time.startswith(today_utc_str))

    if not is_trading_day:
        cron_status = "OK"
    elif scan_age_hours is None:
        # No timestamp parseable — last resort, fall back to date-prefix
        # match so we don't false-alarm on legacy data without isoformat.
        cron_status = "OK" if last_run_today else "FAILED_TODAY"
    elif scan_age_hours <= 26:
        cron_status = "OK"
    elif scan_age_hours <= 48:
        cron_status = "FAILED_TODAY"
    else:
        cron_status = "STALE"

    # ── Stamp actionability (no per-user Kite mapping — model-centric page) ──
    # The Signals page shows the MODEL's book: OPEN (new buys), HOLD (positions the model holds),
    # EXIT (positions to close). Held/exit state is written into the envelope by the paper-book cron;
    # every viewer sees the same model book. Personal-holding tracking lives on the Positions page.
    try:
        signals = _stamp_actionability(signals)
    except Exception as exc:
        logger.warning("actionability stamp failed: %s", exc)

    # The Oct-1 review-readiness scorecard stays operator-only.
    if not getattr(user, "is_admin", False):
        review_scorecard = None

    # Stage-2 immutable floor: freeze each signal the FIRST time it is served. Idempotent +
    # best-effort — never overwrites an existing snapshot and never breaks serving on a fault.
    try:
        from services.signal_snapshots import freeze_signals
        freeze_signals(db, signals, scan_time)
    except Exception:
        pass

    # Per-user mapping (tenant contract, test_signals_portfolio_block_is_per_user): the paper
    # portfolio is the MODEL's shared ₹10L book, not any user's account. Only the admin/owner sees
    # it here (labeled source="paper"); every other user gets a zeroed block (source="none") so the
    # model's NAV can never read as their own balance. A user's real position state lives in THEIR
    # execution ledger (/api/execution/*), never in this shared envelope.
    if user.is_admin:
        portfolio_block = {
            "source": "paper",
            "cash": portfolio.get("cash", 0),
            "total_value": portfolio.get("cash", 0) + sum(
                p.get("current_value", 0) for p in portfolio.get("positions", {}).values()
            ),
            "positions": len(portfolio.get("positions", {})),
            "total_trades": portfolio.get("total_trades", 0),
        }
    else:
        portfolio_block = {"source": "none", "cash": 0, "total_value": 0,
                           "positions": 0, "total_trades": 0}

    return {
        "signals": signals,
        "regime": regime_info,
        "portfolio": portfolio_block,
        "model": {
            "version": model_meta.get("version", "unknown"),
            "trained_at": model_meta.get("last_trained") or model_meta.get("trained_at"),
            "avg_auc": model_meta.get("avg_auc", 0),
            "n_features": model_meta.get("n_features", 0),
        },
        "scan_time": scan_time,
        "n_signals": len(signals),
        "sizing_capital": sizing_capital,
        "sizing_risk_pct": sizing_risk_pct,
        "review_scorecard": review_scorecard,
        **monitor_meta,
        "cron_health": {
            "status": cron_status,
            "expected_today": is_trading_day,
            "last_run_today": last_run_today,
        },
    }


@router.get("/signals/snapshot/{signal_id}")
def get_signal_snapshot(
    signal_id: str,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """The IMMUTABLE frozen snapshot of a signal as first published — the card a user acted
    on, which never changes on a model recompute (Stage-2). Powers dispute defensibility and
    'why did it say X' reproducibility. 404 if the signal_id was never frozen."""
    from services.signal_snapshots import get_snapshot
    snap = get_snapshot(db, signal_id)
    if snap is None:
        raise HTTPException(status_code=404, detail="No frozen snapshot for that signal_id")
    return snap


@router.get("/signals/history")
def get_signal_history(
    model: str = Query("bhanushali", description="Strategy book: 'bhanushali'"),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Active-signal track record: today's signals + still-in-play prior-day
    signals + analytics, for the SignalsV2 / StockDetailV2 history views.

    Replaces the retired Vercel `/fn/signals` serverless function, which read
    the repo's PUBLIC raw URLs and served the data UNAUTHENTICATED. Now the repo
    is private and this endpoint is auth-gated, the data is read server-side via
    the GitHub-first/local-fallback helper (authenticated). Live-price
    enrichment that the Vercel function did client-of-GitHub-side is dropped;
    the frontend's existing price/Kite hooks cover live overlays, and history
    entries already carry their stored status + last_price.
    """
    files = _model_or_400(model)
    today_raw = _read_json_with_fallback(
        RESULTS_DIR / files["today"], f"results/{files['today']}", []
    )
    today = today_raw.get("signals", []) if isinstance(today_raw, dict) else (today_raw or [])
    history = _read_json_with_fallback(
        RESULTS_DIR / files["history"], f"results/{files['history']}", []
    ) or []
    analytics = _read_json_with_fallback(
        RESULTS_DIR / files["analytics"], f"results/{files['analytics']}", {}
    ) or {}
    return {"today": today, "history": history, "analytics": analytics, "source": "backend"}


@router.get("/signals/sell-guidance")
def get_sell_guidance(
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """NQ positions the user should sell now (target / stop / time hit).

    Thin filter over the same builder used by /positions/nq — the
    SignalsV2 page uses this to render the 'Held — Sell Guidance' tier
    headline without pulling all NQ positions just to filter client-side.
    """
    from services.nq_positions import build_nq_positions

    # No per-user broker connection (ADR 0011) — self-reported fills only. Build off the
    # per-user NQOrder ledger with no Kite holdings join (Stage-4/5 wire the self-report source).
    positions = build_nq_positions(user.id, db, kite_holdings=[])
    actionable = [p for p in positions if p["status_for_user"] == "ACTIONABLE_SELL"]
    return {
        "positions": actionable,
        "count": len(actionable),
        "updated_at": datetime.utcnow().isoformat(),
    }


@router.get("/signals/watchlist")
def get_watchlist(
    model: str = Query("bhanushali", description="Strategy book: 'bhanushali'"),
):
    """Borderline candidates from today's scan (conf 0.75-0.92).

    These are signals the model surfaced but didn't clear the entry
    confidence gate (currently 0.92). They're tracked but not buyable —
    surfacing them gives users visibility into what the system is
    monitoring, which is otherwise invisible.

    Reads `results/signals_watchlist.json` written by the cron's
    write step (envelope shape identical to signals_today_weekly.json,
    `tier: 'watchlist'`). Falls back to GitHub raw URL if the local
    file is missing on Render.

    Each signal carries `actionability='WATCHLIST'` so the frontend can
    distinguish "monitoring only" from "buyable now" without parsing
    confidence ranges client-side.
    """
    files = _model_or_400(model)
    if files["watchlist"] is None:            # the weekly book has no watchlist tier
        return {"signals": [], "count": 0, "generated_at": None, "tier": "watchlist"}
    raw = _read_json_with_fallback(
        RESULTS_DIR / files["watchlist"],
        f"results/{files['watchlist']}",
        {},
    )
    # Tolerate both envelope and bare-list shapes for forward compat.
    if isinstance(raw, list):
        signals = raw
        generated_at = None
    else:
        signals = raw.get("signals", []) or []
        generated_at = raw.get("generated_at")

    # Stamp actionability so the frontend treats these uniformly with
    # how the entry-tier signals are rendered (TierSection knows about
    # actionability strings already).
    enriched = []
    for s in _stamp_sector(signals):
        copy = dict(s)
        copy["actionability"] = "WATCHLIST"
        enriched.append(copy)

    return {
        "signals": enriched,
        "count": len(enriched),
        "generated_at": generated_at,
        "tier": "watchlist",
    }


@router.get("/signals/regime")
def get_regime():
    """Current market regime, read from the signals_today_weekly.json envelope.

    The legacy src/regime_detector.py (5-tier) was deleted in the §3.2
    cleanup, so the old import-based path raised on every call and always
    returned UNKNOWN (plus it did risky sys.path / sys.modules surgery). The
    live cron snapshots the v1 strategy's regime into the signals envelope —
    the same block /signals serves — so this reads that single source.
    """
    raw = _read_json_with_fallback(
        RESULTS_DIR / "signals_today_weekly.json", "results/signals_today_weekly.json", {}
    )
    regime = (raw or {}).get("regime") if isinstance(raw, dict) else None
    if regime:
        return {
            "regime": regime.get("status", "UNKNOWN"),
            "strength": regime.get("strength", 0),
            "vix": regime.get("vix", 0),
            "breadth": regime.get("breadth", 0),
        }
    return {"regime": "UNKNOWN", "strength": 0, "vix": 0, "breadth": 0}


@router.post("/signals/scan")
@limiter.limit("2/minute")
async def run_scan(request: Request):
    """
    Return the most recent signals from the daily cron.

    On-demand scanning is retired — the backend does not run the model in-process
    (Render's free-tier RAM can't hold it). Live signal generation happens in a
    single canonical path: the long-horizon scanner
    (``src.runners.long_horizon_cron``, Render cron, 4:15 PM IST weekdays) →
    ``results/signals_today_weekly.json`` → GitHub push.

    This endpoint simply returns the latest cron-published signals so the UI's
    "scan" button behaves like a refresh.
    """
    existing = _read_json_with_fallback(
        RESULTS_DIR / "signals_today_weekly.json", "results/signals_today_weekly.json", []
    )
    # signals_today_weekly.json is an envelope dict {generated_at, signals:[...], regime,
    # ...} in the current cron format (older format was a bare list). Unwrap so the
    # count + payload are the signals array, not the envelope's top-level keys.
    sigs = existing.get("signals", []) if isinstance(existing, dict) else (existing or [])
    return {
        "status": "cached",
        "n_total": len(sigs),
        "signals": sigs,
        "scan_time": datetime.now().isoformat(),
        "message": (
            "Live on-demand scan is retired. Returning the most recent "
            "cron-generated signals; the daily scan runs at 4:15 PM IST "
            "weekdays via Render cron."
        ),
    }
